      </div>
      <!-- FIN CONTENIDO PRINCIPAL -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white mt-2">
        <div class="container-fluid">
          <div class="copyright ">

            <div class="row">

              <div class="col-md-2 text-left">
                    <label> Jairo Pérez Rodríguez</label>
              </div>

              <div class="col-md-2 text-left">
                              <a target="_blank" href="https://www.facebook.com/Jotarwc" class="btn-user btn-block"> <i class="fab fa-facebook-f "></i> Facebook </a>
              </div>

              <div class="col-md-2 text-left">
                          <a target="_blank" href="https://www.instagram.com/jota.rwc" class="btn-user btn-block"> <i class="fab fa-instagram"></i> Instagram </a>                
              </div>
                
              <div class="col-md-6 text-right">
                    Copyright &copy; 2019
              </div>

            </div>
                        
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- FIN LADO IZQ -->

  </div>
  <!-- End of Page Wrapper -->
  