      </div>
      <!-- FIN CONTENIDO PRINCIPAL -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white mt-2">
        <div class="container-fluid">
          <div class="copyright ">

            <div class="row">
              <div class="col-md-12 text-right">
                Copyright &copy;
                <label> Jairo Pérez Rodríguez</label>
              <div>
            </div>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- FIN LADO IZQ -->

  </div>
  <!-- End of Page Wrapper -->
