        <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="Jairo Pérez Rodríguez" content="">

        <?php
                include_once("includes/session.inc");           
        ?>

        <script src="vendor/jquery/jquery.min.js"></script>

        <!-- Custom fonts for this template-->
        <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">        
        <link href="img/icono.jpg" rel="icon">

        <!-- Bootstrap -->
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
        <link href="vendor/bootstrap/bootstrap.min.css" rel="stylesheet">

        <!-- Core plugin JavaScript
        <script src="../vendor/jquery-easing/jquery.easing.min.js"></script> -->

        <!-- Page level plugins 
        <script src="vendor/chart.js/Chart.min.js"></script> -->

        <!-- Page level custom scripts 
        <script src="js/demo/chart-area-demo.js"></script>
        <script src="js/demo/chart-pie-demo.js"></script> -->

        <!-- Datatables -->
        <script src="vendor/datatables/jquery.dataTables.min.js"></script> 
        <script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>
        <link rel="stylesheet" href="vendor/datatables/dataTables.bootstrap4.min.css">
        
        <!-- sweetalert2 -->
        <script src="vendor/SweetAlert/sweetalert2.min.js"></script>
        <link rel="stylesheet" href="vendor/SweetAlert/sweetalert2.min.css">

        <!-- Semantic -->
        <script src="vendor/semantic/semantic.min.js"></script>
        <link rel="stylesheet" href="vendor/semantic/semantic.min.css">

        <!-- Custom styles for this template  -->
        <link href="css/sb-admin-2.min.css" rel="stylesheet">

        <!-- Buscador 
        <script src="js/Buscador.js"></script> -->
