        <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="Jairo Pérez Rodríguez" content="">

        <?php
                include_once("includes/session.inc");           
        ?>

        <!-- Custom fonts for this template  -->
        <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link href="img/icono2.jpg" rel="icon">

        <!-- Bootstrap
        <link href="vendor/bootstrap/bootstrap.min.css" rel="stylesheet"> -->

        <!-- Datatables -->
        <link rel="stylesheet" href="vendor/datatables/dataTables.bootstrap4.min.css">
        
        <!-- sweetalert2 -->
        <link rel="stylesheet" href="vendor/SweetAlert/sweetalert2.min.css">

        <!-- Semantic -->
        <link rel="stylesheet" href="vendor/semantic/semantic.min.css">

        <!-- Custom styles for this template  -->
        <link href="css/sb-admin-2.min.css" rel="stylesheet">

        <!-- Buscador 
        <script src="js/Buscador.js"></script> -->
